name: Arduino CLI CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Arduino CLI
      uses: arduino/setup-arduino-cli@v1.0.0
    - name: Install STM libs
      run: |
        arduino-cli config init --additional-urls https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json
        arduino-cli config dump
        arduino-cli core update-index
        arduino-cli core install STM32:stm32
        arduino-cli lib install LiquidCrystal
        arduino-cli lib install "Analog Buttons"
        sed -i '/recipe.output.tmp_file={build.project_name}.hex/d' "$HOME/.arduino15/packages/STM32/hardware/stm32/1.8.0/platform.txt"
        sed -i '/recipe.output.save_file={build.project_name}.{build.variant}.hex/d' "$HOME/.arduino15/packages/STM32/hardware/stm32/1.8.0/platform.txt"
    - name: Build prod
      run: |
        arduino-cli compile --fqbn STM32:stm32:Nucleo_64:opt=o3std,pnum=NUCLEO_F411RE --verbose src/arduino/respi-prod.cpp
        mkdir dist/
        VERSION=$(sed -En 's/#define VERSION[ ]+["](.+)["]/\1/p' src/arduino/parameters.h)
        cp src/arduino/respi-prod.cpp.STM32.stm32.Nucleo_64.bin "dist/respi-prod-$VERSION.bin"
    - name: Build qualification
      run: |
        sed -i 's/#define MODE MODE_PROD/#define MODE MODE_QUALIFICATION/' src/arduino/config.h
        arduino-cli compile --fqbn STM32:stm32:Nucleo_64:opt=o3std,pnum=NUCLEO_F411RE --verbose src/arduino/respi-prod.cpp
        mkdir dist/
        VERSION=$(sed -En 's/#define VERSION[ ]+["](.+)["]/\1/p' src/arduino/parameters.h)
        cp src/arduino/respi-prod.cpp.STM32.stm32.Nucleo_64.bin "dist/respi-qualification-$VERSION.bin"
    - name: Archive binaries
      uses: actions/upload-artifact@v1
      with:
        name: bin
        path: dist/
